apiVersion: v1
kind: Secret
metadata:
  name: movie-secret
  namespace: jenkins
type: kubernetes.io/basic-auth
stringData:
  username: 'movie_db_username'
  password: 'movie_db_password'
---  
apiVersion: v1
kind: Secret
metadata:
  name: cast-secret
  namespace: jenkins
type: kubernetes.io/basic-auth
stringData:
  username: 'cast_db_username'
  password: 'cast_db_password'